### ISSUE TITLE
Error import pykinect2 

### ISSUE THREAD

**Issue by H4Njx** [kiddos/pykinect2#4]
i run the test_kinect2.py and got the error
Traceback (most recent call last):
  File "/home/hanjx/anaconda3/envs/pykinect2/lib/python3.6/site-packages/kinect2.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "/home/hanjx/anaconda3/envs/pykinect2/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named '_kinect2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hanjx/PycharmProjects/pythonProject/pypy.py", line 2, in <module>
    from kinect2 import Kinect2
  File "/home/hanjx/anaconda3/envs/pykinect2/lib/python3.6/site-packages/kinect2.py", line 17, in <module>
    _kinect2 = swig_import_helper()
  File "/home/hanjx/anaconda3/envs/pykinect2/lib/python3.6/site-packages/kinect2.py", line 16, in swig_import_helper
    return importlib.import_module('_kinect2')
  File "/home/hanjx/anaconda3/envs/pykinect2/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_kinect2'

Process finished with exit code 1

**Comment by kiddos** [comment]
Hi
I never build it under anaconda settings before. Can you show me your build setting, so I can try to replicate this?

**Comment by zhuohoudeputao** [comment]
ImportError: /home/yjs/.local/lib/python3.8/site-packages/_kinect2.so: undefined symbol: clBuildProgram

I meet this error

**Comment by zhuohoudeputao** [comment]
[main] Building folder: pykinect2 
[main] Configuring folder: pykinect2 
[proc] Executing command: /usr/bin/cmake --no-warn-unused-cli -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_BUILD_TYPE:STRING=Debug -DCMAKE_C_COMPILER:FILEPATH=/bin/x86_64-linux-gnu-gcc-8 -DCMAKE_CXX_COMPILER:FILEPATH=/bin/x86_64-linux-gnu-g++-8 -H/home/yjs/Development/pykinect2 -B/home/yjs/Development/pykinect2/build -G "Unix Makefiles"
[cmake] Not searching for unused variables given on the command line.
[cmake] -- The C compiler identification is GNU 8.4.0
[cmake] -- The CXX compiler identification is GNU 8.4.0
[cmake] -- Check for working C compiler: /bin/x86_64-linux-gnu-gcc-8
[cmake] -- Check for working C compiler: /bin/x86_64-linux-gnu-gcc-8 -- works
[cmake] -- Detecting C compiler ABI info
[cmake] -- Detecting C compiler ABI info - done
[cmake] -- Detecting C compile features
[cmake] -- Detecting C compile features - done
[cmake] -- Check for working CXX compiler: /bin/x86_64-linux-gnu-g++-8
[cmake] -- Check for working CXX compiler: /bin/x86_64-linux-gnu-g++-8 -- works
[cmake] -- Detecting CXX compiler ABI info
[cmake] -- Detecting CXX compiler ABI info - done
[cmake] -- Detecting CXX compile features
[cmake] -- Detecting CXX compile features - done
[cmake] -- Found numpy.i
[cmake] -- Found SWIG: /usr/bin/swig4.0 (found version "4.0.1") 
[cmake] -- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.8.so (found suitable version "3.8.5", minimum required is "3") 
[cmake] -- Looking for CL_VERSION_2_2
[cmake] -- Looking for CL_VERSION_2_2 - found
[cmake] -- Found OpenCL: /usr/lib/x86_64-linux-gnu/libOpenCL.so (found version "2.2") 
[cmake] CMake Warning (dev) at /usr/share/cmake-3.16/Modules/FindOpenGL.cmake:275 (message):
[cmake]   Policy CMP0072 is not set: FindOpenGL prefers GLVND by default when
[cmake]   available.  Run "cmake --help-policy CMP0072" for policy details.  Use the
[cmake]   cmake_policy command to set the policy and suppress this warning.
[cmake] 
[cmake]   FindOpenGL found both a legacy GL library:
[cmake] 
[cmake]     OPENGL_gl_LIBRARY: /usr/lib/x86_64-linux-gnu/libGL.so
[cmake] 
[cmake]   and GLVND libraries for OpenGL and GLX:
[cmake] 
[cmake]     OPENGL_opengl_LIBRARY: /usr/lib/x86_64-linux-gnu/libOpenGL.so
[cmake]     OPENGL_glx_LIBRARY: /usr/lib/x86_64-linux-gnu/libGLX.so
[cmake] 
[cmake]   OpenGL_GL_PREFERENCE has not been set to "GLVND" or "LEGACY", so for
[cmake]   compatibility with CMake 3.10 and below the legacy GL library will be used.
[cmake] Call Stack (most recent call first):
[cmake]   src/CMakeLists.txt:18 (find_package)
[cmake] This warning is for project developers.  Use -Wno-dev to suppress it.
[cmake] 
[cmake] -- Found OpenGL: /usr/lib/x86_64-linux-gnu/libOpenGL.so   
[cmake] -- found OpenGL
[cmake] -- found OpenCL
[cmake] -- using libraries: /home/yjs/Development/pykinect2/build/third_party/lib/libfreenect2.a;/usr/lib/x86_64-linux-gnu/libglfw.so;/usr/lib/x86_64-linux-gnu/libusb-1.0.so;/usr/lib/x86_64-linux-gnu/libGL.so;/usr/lib/x86_64-linux-gnu/libGLU.so;/usr/lib/x86_64-linux-gnu/libturbojpeg.so;/usr/lib/x86_64-linux-gnu/libjpeg.so;/usr/lib/libOpenNI2.so
[cmake] -- Using PythonLibs 3.8.5
[cmake] -- Looking for pthread.h
[cmake] -- Looking for pthread.h - found
[cmake] -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
[cmake] -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
[cmake] -- Looking for pthread_create in pthreads
[cmake] -- Looking for pthread_create in pthreads - not found
[cmake] -- Looking for pthread_create in pthread
[cmake] -- Looking for pthread_create in pthread - found
[cmake] -- Found Threads: TRUE  
[cmake] -- Found CUDA: /usr/local/cuda-11.2 (found version "11.2") 
[cmake] CMake Warning (dev) at /usr/share/cmake-3.16/Modules/UseSWIG.cmake:607 (message):
[cmake]   Policy CMP0078 is not set: UseSWIG generates standard target names.  Run
[cmake]   "cmake --help-policy CMP0078" for policy details.  Use the cmake_policy
[cmake]   command to set the policy and suppress this warning.
[cmake] 
[cmake] Call Stack (most recent call first):
[cmake]   src/CMakeLists.txt:96 (SWIG_ADD_LIBRARY)
[cmake] This warning is for project developers.  Use -Wno-dev to suppress it.
[cmake] 
[cmake] CMake Warning (dev) at /usr/share/cmake-3.16/Modules/UseSWIG.cmake:460 (message):
[cmake]   Policy CMP0086 is not set: UseSWIG honors SWIG_MODULE_NAME via -module
[cmake]   flag.  Run "cmake --help-policy CMP0086" for policy details.  Use the
[cmake]   cmake_policy command to set the policy and suppress this warning.
[cmake] 
[cmake] Call Stack (most recent call first):
[cmake]   /usr/share/cmake-3.16/Modules/UseSWIG.cmake:702 (SWIG_ADD_SOURCE_TO_MODULE)
[cmake]   src/CMakeLists.txt:96 (SWIG_ADD_LIBRARY)
[cmake] This warning is for project developers.  Use -Wno-dev to suppress it.
[cmake] 
[cmake] -- Configuring done
[cmake] -- Generating done
[cmake] -- Build files have been written to: /home/yjs/Development/pykinect2/build
[build] Starting build
[proc] Executing command: /usr/bin/cmake --build /home/yjs/Development/pykinect2/build --config Debug --target all -j 18 --
[build] Scanning dependencies of target gtest
[build] Scanning dependencies of target libfreenect2
[build] [ 15%] Completed 'libfreenect2'
[build] [ 15%] Completed 'gtest'
[build] [ 15%] Built target kinect2_swig_compilation
[build] [ 75%] Built target gtest
[build] [ 85%] Built target libfreenect2
[build] [100%] Built target _kinect2
[build] Build finished with exit code 0

This is my build log.

**Comment by kiddos** [comment]
I'm guessing it was because of this typo
`${OPENCL_LIBRARIES}` should be `${OpenCL_LIBRARIES}`.

**Comment by guningquan** [comment]
you should input   "pip install -e .", install of sudo pip install .
